""" Collection of conversation states, used in bot """

DAY_OF_WEEK = 'DAY_OF_WEEK'
WHOM_TO_SEND = 'WHO_TO_SEND'
PREPARE_MAILING = 'PREPARE_MAILING'
ASK_EMAIL = 'ASK_EMAIL'
ASK_CITY = 'ASK_CITY'
SCHEDULE = 'SCHEDULE'
SETTINGS = 'SETTINGS'
LECTURERS_SCHEDULE = 'LECT_SCHEDULE'
